In [1]:
import entwine


ModuleNotFoundError: No module named 'entwine'

In [1]:
build -i https://data.entwine.io/red-rocks.laz -o ~/entwine/red-rocks

SyntaxError: invalid syntax (1062552923.py, line 1)

In [19]:
las = laspy.read("2560_1145.las")

In [22]:
las

<LasData(1.2, point fmt: <PointFormat(1, 0 bytes of extra dims)>, 29525816 points, 0 vlrs)>

In [23]:
list(las.point_format.dimension_names)

['X',
 'Y',
 'Z',
 'intensity',
 'return_number',
 'number_of_returns',
 'scan_direction_flag',
 'edge_of_flight_line',
 'classification',
 'synthetic',
 'key_point',
 'withheld',
 'scan_angle_rank',
 'user_data',
 'point_source_id',
 'gps_time']

In [24]:
las.X

array([    0,     0,     0, ..., 19208, 19236, 34290])

In [25]:
las.intensity

array([371, 122, 321, ..., 146,  58,  61], dtype=uint16)

In [26]:
las.gps_time

array([2.23558158e+08, 2.23558158e+08, 2.23558158e+08, ...,
       2.23621618e+08, 2.23621618e+08, 2.23621622e+08])

In [27]:
set(list(las.classification))

{1, 2, 3, 6, 17}

In [28]:
point_data = np.stack([las.X, las.Y, las.Z], axis=0).transpose((1, 0))

In [29]:
point_data

array([[    0, 25638, 85398],
       [    0, 24538, 85490],
       [    0, 20360, 87737],
       ...,
       [19208, 90613, 82746],
       [19236, 90573, 82756],
       [34290, 90896, 83089]])

In [30]:
buildings = laspy.create(point_format=las.header.point_format, file_version=las.header.version)
buildings.points = las.points[las.classification == 6]

In [32]:
buildings.write("buildings.las")

In [33]:
geom = o3d.geometry.PointCloud()
geom.points = o3d.utility.Vector3dVector(point_data)
o3d.visualization.draw_geometries([geom])